#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["emendatusenigmatica", "thermal", "minecraft", "tconstruct", "tmechworks", "create", "immersiveengineering", "mekanism"]

