
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "f029f3fb"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "c01dadad"
	#The color for the background of the tooltip.
	background = "d0001010"

