
#所有的配置选项都与核心玩法有关
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [默认: true]
	enablecitizenvoices = true
	#默认情况下，当在一个建筑附近放置其它建筑时，已经放置的建筑会显示它们等级 5 时候的预览，并且会有蓝色的轮廓线包围着。设置为 false 以关闭此功能。 [默认: true]
	neighborbuildingrendering = true
	#当启用时，殖民地的边界将在拿着建筑工具时以团队颜色显示；当关闭时，你所在的殖民地将会变白，其他所有的殖民地将会变红。 [默认: true]
	colonyteamborders = true

