
[general]
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[enabledMappers]
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Recipe mapper for custom recipes that don't implement IRecipe
	ProjectEIntegrationRecipeMapper = true

[CraftingMapper]

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

	[CraftingMapper.MekItemStackToGas]
		#Maps Mekanism item stack to gas recipes. (Gas conversion, Oxidizing)
		enabled = true

	[CraftingMapper.MekCombiner]
		#Maps Mekanism combiner recipes.
		enabled = true

	[CraftingMapper.MekElectrolysis]
		#Maps Mekanism electrolytic separator recipes.
		enabled = true

	[CraftingMapper.MekItemStackToInfuseType]
		#Maps Mekanism item stack to infuse type conversion recipes.
		enabled = true

	[CraftingMapper.MekChemicalInfuser]
		#Maps Mekanism chemical infuser recipes.
		enabled = true

	[CraftingMapper.MekRotary]
		#Maps Mekanism rotary condensentrator recipes.
		enabled = true

	[CraftingMapper.MekGasToGas]
		#Maps Mekanism activating and centrifuging recipes.
		enabled = true

	[CraftingMapper.MekDissolution]
		#Maps Mekanism dissolution recipes.
		enabled = true

	[CraftingMapper.MekFluidSlurryToSlurry]
		#Maps Mekanism washing recipes.
		enabled = true

	[CraftingMapper.MekMetallurgicInfuser]
		#Maps Mekanism metallurgic infuser recipes.
		enabled = true

	[CraftingMapper.MekItemStackGasToItemStack]
		#Maps Mekanism Machine recipes that go from item, gas to item. (Compressing, Purifying, Injecting)
		enabled = true

	[CraftingMapper.MekChemicalCrystallizer]
		#Maps Mekanism crystallizing recipes.
		enabled = true

	[CraftingMapper.MekPressurizedReaction]
		#Maps Mekanism pressurized reaction recipes.
		enabled = true

	[CraftingMapper.MekSawmill]
		#Maps Mekanism sawmill recipes. (Disabled by default, due to causing various EMC values to be removed pertaining to charcoal/wood)
		enabled = false

	[CraftingMapper.MekItemStackToItemStack]
		#Maps Mekanism Machine recipes that go from item to item. (Crushing, Enriching, Smelting)
		enabled = true

	[CraftingMapper.MekFluidToFluid]
		#Maps Mekanism evaporating recipes.
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.PsiTrickMapper]
		#Maps Psi trick crafting recipes
		enabled = true

	[CraftingMapper.MysticalAgricultureReprocessorMapper]
		#Recipe mapper for Mystical Agriculture seed reprocessor recipes
		enabled = false

	[CraftingMapper.MysticalAgricultureInfusionMapper]
		#Recipe mapper for Mystical Agriculture infusion recipes
		enabled = false

	[CraftingMapper.ImmersiveEngineeringSawmillMapper]
		#Recipe mapper for Immersive Engineering Sawmill recipes
		enabled = true

	[CraftingMapper.ImmersiveEngineeringMixerMapper]
		#Recipe mapper for Immersive Engineering Mixer recipes
		enabled = true

	[CraftingMapper.ImmersiveEngineeringMetalPressMapper]
		#Recipe mapper for Immersive Engineering Metal Press recipes
		enabled = true

	[CraftingMapper.ImmersiveEngineeringCrusherMapper]
		#Recipe mapper for Immersive Engineering Crusher recipes
		enabled = true

	[CraftingMapper.ImmersiveEngineeringCokeOvenMapper]
		#Recipe mapper for Immersive Engineering Coke Oven recipes
		enabled = true

	[CraftingMapper.ImmersiveEngineeringBlastFurnaceMapper]
		#Recipe mapper for Immersive Engineering Blast Furnace recipes
		enabled = true

	[CraftingMapper.ImmersiveEngineeringAlloyMapper]
		#Recipe mapper for Immersive Engineering Alloy recipes
		enabled = true

	[CraftingMapper.DraconicEvolutionFusionMapper]
		#Recipe mapper for Draconic Evolution Fusion recipes
		enabled = true

	[CraftingMapper.CreateSplashingMapper]
		#Create Splashing Mapper
		enabled = true

	[CraftingMapper.CreateSandpaperPolishingMapper]
		#Create Sandpaper Polishing Mapper
		enabled = true

	[CraftingMapper.CreatePressingMapper]
		#Create Pressing Mapper
		enabled = true

	[CraftingMapper.CreateCUTTINGMapper]
		#Create CUTTING Mapper
		enabled = true

	[CraftingMapper.CreateMillingMapper]
		#Create Milling Mapper
		enabled = true

	[CraftingMapper.CreateDeployerApplicationMapper]
		#Create Deployer Application Mapper
		enabled = true

	[CraftingMapper.CreateCuttingMapper]
		#Create Cutting Mapper
		enabled = true

	[CraftingMapper.CreateCrushingMapper]
		#Create Crushing Mapper
		enabled = true

	[CraftingMapper.CreateCompactingMapper]
		#Create Compacting Mapper
		enabled = true

	[CraftingMapper.CreateBASINMapper]
		#Create BASIN Mapper
		enabled = true

	[CraftingMapper.BotaniaTerraPlateMapper]
		#null
		enabled = true

	[CraftingMapper.BotaniaRuneAlterMapper]
		#null
		enabled = true

	[CraftingMapper.BotaniaPureDaisyMapper]
		#null
		enabled = true

	[CraftingMapper.BotaniaPetalMapper]
		enabled = true

	[CraftingMapper.BotaniaManaInfusionMapper]
		#null
		enabled = true

	[CraftingMapper.BotaniaElvenTradeMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicTartaricForgeMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicBloodAltarMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicAlchemicalReactionChamberMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicAlchemyTableMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicAlchemyArrayMapper]
		#null
		enabled = true

	[CraftingMapper.AstralSorceryWellLiquefactionMapper]
		#A recipe mapper for Astral Sorcery Well Liquefaction recipes. Disabled by default. Maps 1 Item to 1 bucket (1000)
		enabled = false

	[CraftingMapper.AstralSorceryLiquidInfusionMapper]
		#A recipe mapper for Astral Sorcery Liquid Infusion recipes.
		enabled = true

	[CraftingMapper.AstralSorceryBlockTransmutationMapper]
		#A recipe mapper for Astral Sorcery Block Transmutation recipes.
		enabled = true

	[CraftingMapper.AstralSorceryAltarMapper]
		#A recipe mapper for Astral Sorcery Altar recipes.
		enabled = true

	[CraftingMapper.FarmersDelightCuttingBoardMapper]
		#null
		enabled = true

	[CraftingMapper.FarmersDelightCookingPotMapper]
		#null
		enabled = true

	[CraftingMapper.TinkersConstructAlloyingMapper]
		#Mapper for Tinker's Construct Alloying recipes
		enabled = true

	[CraftingMapper.TinkersConstructCastingMapper]
		#Mapper for Tinker's Construct Casting recipes
		enabled = true

	[CraftingMapper.TinkersConstructMeltingMapper]
		#Mapper for Tinker's Construct Melting recipes
		enabled = true

	[CraftingMapper.MekItemStackToPigment]
		#Maps Mekanism item stack to pigment recipes. (Pigment Extracting)
		enabled = true

	[CraftingMapper.MekPaintingMachine]
		#Maps Mekanism painting machine recipes.
		enabled = true

	[CraftingMapper.MekPigmentMixer]
		#Maps Mekanism pigment mixer recipes.
		enabled = true

	[CraftingMapper.AppliedEnergisticsInscriberMapper]
		#Recipe mapper for Applied Energistics inscriber
		enabled = true

	[CraftingMapper.AppliedEnergisticsGrinderMapper]
		#Recipe mapper for Applied Energistics grinder. NOTE: Optional outputs are ignored
		enabled = true

	[CraftingMapper.EnderCrafter]
		#Maps extended crafting Ender Crafter recipes
		enabled = true

	[CraftingMapper.Table]
		#Maps Extended Crafting Table recipes
		enabled = true

	[CraftingMapper.Combination]
		#Maps Extended Crafting Combination recipes
		enabled = true

	[CraftingMapper.Compressor]
		#Maps the Extended Crafting compressor recipes
		enabled = true

	[CraftingMapper.ExtendedCraftingEnderCrafterMapper]
		#Maps extended crafting Ender Crafter recipes
		enabled = true

	[CraftingMapper.ExtendedCraftingTableMapper]
		#Maps Extended Crafting Table recipes
		enabled = true

	[CraftingMapper.IndustrialForegoingStoneWorksGenerateMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Stone Works Generate Mapper. Required Mods: [industrialforegoing] NOTE: Disabled by default.
		enabled = false

	[CraftingMapper.IndustrialForegoingDissolutionChamberMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Dissolution Chamber Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.IndustrialForegoingCrusherMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Crusher Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.ExtendedCraftingCombinationMapper]
		#Maps Extended Crafting Combination recipes
		enabled = true

	[CraftingMapper.ExtendedCraftingCompressorMapper]
		#ProjectE-Integration Recipe Mapper for Extended Crafting Compressor Mapper. Required Mods: [extendedcrafting]
		enabled = true

	[CraftingMapper.TouhoutLittleMaidAltarMapper]
		#ProjectE-Integration Recipe Mapper for Touhout Little Maid Altar Mapper. Required Mods: [touhou_little_maid]
		enabled = true

